
require("./ProjectCatalogEditor.module.css");
const styles = {
  card: 'card_d3d7b6d2',
  title: 'title_d3d7b6d2',
  grid: 'grid_d3d7b6d2',
  fieldFull: 'fieldFull_d3d7b6d2',
  field: 'field_d3d7b6d2',
  label: 'label_d3d7b6d2',
  labelRow: 'labelRow_d3d7b6d2',
  sensitiveToggle: 'sensitiveToggle_d3d7b6d2',
  input: 'input_d3d7b6d2',
  select: 'select_d3d7b6d2',
  inputLocked: 'inputLocked_d3d7b6d2',
  fieldHint: 'fieldHint_d3d7b6d2',
  detailsGrid: 'detailsGrid_d3d7b6d2',
  detailsField: 'detailsField_d3d7b6d2',
  statusPicker: 'statusPicker_d3d7b6d2',
  statusCard: 'statusCard_d3d7b6d2',
  statusDot: 'statusDot_d3d7b6d2',
  statusOpen: 'statusOpen_d3d7b6d2',
  statusArchived: 'statusArchived_d3d7b6d2',
  statusWaitingApproval: 'statusWaitingApproval_d3d7b6d2',
  statusHidden: 'statusHidden_d3d7b6d2',
  statusCardOpen: 'statusCardOpen_d3d7b6d2',
  statusCardSelected: 'statusCardSelected_d3d7b6d2',
  statusCardArchived: 'statusCardArchived_d3d7b6d2',
  statusCardWaitingApproval: 'statusCardWaitingApproval_d3d7b6d2',
  statusCardHidden: 'statusCardHidden_d3d7b6d2',
  footer: 'footer_d3d7b6d2',
  statusMsg: 'statusMsg_d3d7b6d2',
  statusError: 'statusError_d3d7b6d2',
  btnSave: 'btnSave_d3d7b6d2',
  btnCancel: 'btnCancel_d3d7b6d2',
  releaseBalance: 'releaseBalance_d3d7b6d2',
  releaseBalanceStat: 'releaseBalanceStat_d3d7b6d2',
  releaseBalanceValue: 'releaseBalanceValue_d3d7b6d2',
  releaseBalanceCaption: 'releaseBalanceCaption_d3d7b6d2',
  releaseBalanceSep: 'releaseBalanceSep_d3d7b6d2',
  releaseBalanceDone: 'releaseBalanceDone_d3d7b6d2',
  releaseBalanceOver: 'releaseBalanceOver_d3d7b6d2',
  releaseTable: 'releaseTable_d3d7b6d2',
  releaseTableUnits: 'releaseTableUnits_d3d7b6d2',
  releaseTableInput: 'releaseTableInput_d3d7b6d2',
  releaseTableUnitsInput: 'releaseTableUnitsInput_d3d7b6d2',
  releaseTableNotes: 'releaseTableNotes_d3d7b6d2',
  releaseTableEmpty: 'releaseTableEmpty_d3d7b6d2'
};

export default styles;
