
require("./ProjectRowDashboard.module.css");
const styles = {
  card: 'card_57bc4aa3',
  cardActive: 'cardActive_57bc4aa3',
  cardArchived: 'cardArchived_57bc4aa3',
  cardActionsOpen: 'cardActionsOpen_57bc4aa3',
  header: 'header_57bc4aa3',
  headerActive: 'headerActive_57bc4aa3',
  projectInfo: 'projectInfo_57bc4aa3',
  projectNumber: 'projectNumber_57bc4aa3',
  projectTitle: 'projectTitle_57bc4aa3',
  projectSubtitle: 'projectSubtitle_57bc4aa3',
  woTag: 'woTag_57bc4aa3',
  storageAlert: 'storageAlert_57bc4aa3',
  unitsTag: 'unitsTag_57bc4aa3',
  projectCustomer: 'projectCustomer_57bc4aa3',
  noGates: 'noGates_57bc4aa3',
  noGatesRow: 'noGatesRow_57bc4aa3',
  settingsFallbackBtn: 'settingsFallbackBtn_57bc4aa3',
  settingsFallbackBtnActive: 'settingsFallbackBtnActive_57bc4aa3',
  actionsSection: 'actionsSection_57bc4aa3',
  taskSection: 'taskSection_57bc4aa3',
  archivedSummary: 'archivedSummary_57bc4aa3',
  archivedSectionToggles: 'archivedSectionToggles_57bc4aa3',
  archivedSectionToggleActive: 'archivedSectionToggleActive_57bc4aa3',
  archivedBadge: 'archivedBadge_57bc4aa3',
  archivedDate: 'archivedDate_57bc4aa3',
  archivedFileName: 'archivedFileName_57bc4aa3',
  archivedReportPanel: 'archivedReportPanel_57bc4aa3',
  archivedReportToolbar: 'archivedReportToolbar_57bc4aa3',
  archivedReportLink: 'archivedReportLink_57bc4aa3',
  archivedReportJsonLink: 'archivedReportJsonLink_57bc4aa3',
  archivedReportFrame: 'archivedReportFrame_57bc4aa3',
  archivedDynamicReport: 'archivedDynamicReport_57bc4aa3',
  archivedReportSection: 'archivedReportSection_57bc4aa3',
  archivedReportSectionHeader: 'archivedReportSectionHeader_57bc4aa3',
  archivedReportEyebrow: 'archivedReportEyebrow_57bc4aa3',
  archivedReportSummaryGrid: 'archivedReportSummaryGrid_57bc4aa3',
  archivedTableWrap: 'archivedTableWrap_57bc4aa3',
  archivedReportTable: 'archivedReportTable_57bc4aa3',
  archivedLogGate: 'archivedLogGate_57bc4aa3',
  archivedLogGrid: 'archivedLogGrid_57bc4aa3',
  noArchivedReport: 'noArchivedReport_57bc4aa3'
};

export default styles;
