
require("./TaskCard.module.css");
const styles = {
  'task-card': 'task-card_206faa8a',
  'task-card-header': 'task-card-header_206faa8a',
  'task-title': 'task-title_206faa8a',
  'task-btn-group': 'task-btn-group_206faa8a',
  'task-reorder-card': 'task-reorder-card_206faa8a',
  'task-nav-card': 'task-nav-card_206faa8a',
  'task-button-nav': 'task-button-nav_206faa8a',
  'task-actions-card': 'task-actions-card_206faa8a',
  'task-btn-spacer': 'task-btn-spacer_206faa8a',
  'task-button': 'task-button_206faa8a',
  'task-button-save': 'task-button-save_206faa8a',
  'task-button-label': 'task-button-label_206faa8a',
  'task-button-close': 'task-button-close_206faa8a',
  'task-card-row': 'task-card-row_206faa8a',
  'task-card-body': 'task-card-body_206faa8a',
  'task-card-column': 'task-card-column_206faa8a',
  'task-form': 'task-form_206faa8a',
  'form-row': 'form-row_206faa8a',
  field: 'field_206faa8a',
  'field-unit-wrap': 'field-unit-wrap_206faa8a',
  'field-xs': 'field-xs_206faa8a',
  'field-pct': 'field-pct_206faa8a',
  'field-half': 'field-half_206faa8a',
  'field-full': 'field-full_206faa8a',
  'field-right-group': 'field-right-group_206faa8a',
  'field-group-label': 'field-group-label_206faa8a',
  'input-fixed': 'input-fixed_206faa8a',
  'input-fixed-50': 'input-fixed-50_206faa8a',
  'field-unit': 'field-unit_206faa8a',
  'input-small': 'input-small_206faa8a',
  'select-complete': 'select-complete_206faa8a',
  'gate-edit-toggle': 'gate-edit-toggle_206faa8a',
  'gate-edit-track': 'gate-edit-track_206faa8a',
  'gate-edit-thumb': 'gate-edit-thumb_206faa8a',
  'gate-edit-label': 'gate-edit-label_206faa8a',
  'gate-rename-toggle': 'gate-rename-toggle_206faa8a',
  'gate-rename-label': 'gate-rename-label_206faa8a',
  'completion-warning': 'completion-warning_206faa8a',
  'tab-bar': 'tab-bar_206faa8a',
  'tab-btn': 'tab-btn_206faa8a',
  'tab-active': 'tab-active_206faa8a',
  'tab-content': 'tab-content_206faa8a',
  'tab-placeholder': 'tab-placeholder_206faa8a',
  'evidence-edit': 'evidence-edit_206faa8a',
  'icon-small': 'icon-small_206faa8a',
  spinning: 'spinning_206faa8a',
  'tc-spin': 'tc-spin_206faa8a'
};

export default styles;
