
require("./UserManualPanel.module.css");
const styles = {
  overlay: 'overlay_cb978ebd',
  fadeIn: 'fadeIn_cb978ebd',
  panel: 'panel_cb978ebd',
  slideIn: 'slideIn_cb978ebd',
  panelHeader: 'panelHeader_cb978ebd',
  panelTitle: 'panelTitle_cb978ebd',
  closeBtn: 'closeBtn_cb978ebd',
  body: 'body_cb978ebd',
  sidebar: 'sidebar_cb978ebd',
  navGroupLabel: 'navGroupLabel_cb978ebd',
  navLink: 'navLink_cb978ebd',
  navActive: 'navActive_cb978ebd',
  navNum: 'navNum_cb978ebd',
  sidebarFooter: 'sidebarFooter_cb978ebd',
  content: 'content_cb978ebd',
  hero: 'hero_cb978ebd',
  heroLabel: 'heroLabel_cb978ebd',
  heroTitle: 'heroTitle_cb978ebd',
  heroDesc: 'heroDesc_cb978ebd',
  section: 'section_cb978ebd',
  sectionTitle: 'sectionTitle_cb978ebd',
  num: 'num_cb978ebd',
  item: 'item_cb978ebd',
  itemIcon: 'itemIcon_cb978ebd',
  itemBody: 'itemBody_cb978ebd',
  itemTitle: 'itemTitle_cb978ebd',
  itemDesc: 'itemDesc_cb978ebd',
  mockup: 'mockup_cb978ebd',
  mockHeader: 'mockHeader_cb978ebd',
  mockTitle: 'mockTitle_cb978ebd',
  mockBtns: 'mockBtns_cb978ebd',
  mockBtn: 'mockBtn_cb978ebd',
  mockBadges: 'mockBadges_cb978ebd',
  mockBadge: 'mockBadge_cb978ebd',
  bg: 'bg_cb978ebd',
  by: 'by_cb978ebd',
  br: 'br_cb978ebd',
  bn: 'bn_cb978ebd',
  mockSearch: 'mockSearch_cb978ebd',
  badgeGrid: 'badgeGrid_cb978ebd',
  bc: 'bc_cb978ebd',
  bcGreen: 'bcGreen_cb978ebd',
  bcYellow: 'bcYellow_cb978ebd',
  bcRed: 'bcRed_cb978ebd',
  bcGray: 'bcGray_cb978ebd',
  bcName: 'bcName_cb978ebd',
  bcDesc: 'bcDesc_cb978ebd',
  chip: 'chip_cb978ebd',
  chipGreen: 'chipGreen_cb978ebd',
  chipYellow: 'chipYellow_cb978ebd',
  chipRed: 'chipRed_cb978ebd',
  chipGray: 'chipGray_cb978ebd',
  dot: 'dot_cb978ebd',
  tip: 'tip_cb978ebd',
  steps: 'steps_cb978ebd',
  step: 'step_cb978ebd',
  sortDemo: 'sortDemo_cb978ebd',
  sortLabel: 'sortLabel_cb978ebd',
  sortPill: 'sortPill_cb978ebd',
  sortPillActive: 'sortPillActive_cb978ebd',
  chipRow: 'chipRow_cb978ebd',
  manualFooter: 'manualFooter_cb978ebd'
};

export default styles;
